# handler
reset_command = "reset"
my_prompts_command = "my_prompts"
create_new_prompt_command = "create_new_prompt"
gen_image_command = "gen_image"
document_command = "document"
translator_command = "translator"
my_assistants_command = "my_assistants"
create_new_assistant_command = "create_new_assistant"
admin_command = "admin"
