# handler
model_switch_command = "switch_model"
linux_terminal_command = "linux_terminal"
translator_command = "translator"
rewrite_command = "rewrite"
cyber_secrity_command = "cyber_secrity"
etymologists_command = "etymologists"
genius_command = "genius"
reset_command = "reset"
document_command = "document"
gen_image_command = "gen_image"
admin_command = "admin"
